language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
# command to install dependencies
install:
  - pip install .
  - pip install nose
# command to run tests
script: nosetests
